### ISSUE TITLE
explaining contents of model finder output

### ISSUE THREAD

**Issue by GavinHuttley** [iqtree/piqtree#102]
For the model finder, it returns content like
```
{'F81+F+G4': '-22031.57915 35 3.393933387', 'F81+F+I+G4': '-22019.14569 36 3.498599912', 'GTR+F': '-22701.4875 39 2.863213275', 'GTR+F+G4': '-21155.96905 40 4.183274952', 'GTR+F+I': '-21615.54758 40 3.157092513', 'GTR+F+I+G4': '-21148.84917 41 4.227880748', 'GTR+F+I+R2': '-21174.43313 42 3.977727243', 'GTR+F+I+R3': '-21146.99716 44 4.178975537', 'GTR+F+I+R4': '-21146.7857 46 4.178022765', 'GTR+F+R2': '-21235.65958 41 3.654268215', 'GTR+F+R3': '-21147.07793 43 4.129785335', 'GTR+F+R4': '-21146.62676 45 4.146373298', 'HKY+F+G4': '-21489.74786 36 4.227190047'...
```
For the first of these, 'F81+F+G4', I need to confirm what the components are. Hopefully the C++ variable names will help '-22031.57915 35 3.393933387' where '-22031.57915' is the log-likelihood, '35' is the degrees of freedom (or number of free parameters) but '3.393933387'? 

Other contents in there?

**Comment by GavinHuttley** [comment]
the third value is tree length

**Comment by GavinHuttley** [comment]
write a dataclass `ModelResultValue` for the values of the dict above which has 3 attributes: `lnL: float` for the first field,l `nfp: int` for the second field and `tree_length: float` for the third.

**Comment by KatherineCaley** [comment]
I'll take this on!

**Comment by GavinHuttley** [comment]
`piqtree2/iqtree/_model_finder.py` line 58. argument `val` corresponds to the entries above (`-22031.57915 35 3.393933387`).

`val` should be a `ModelResultValue` instance which has the attributes as defined above.
