### ISSUE TITLE
substitution models need an Enum

### ISSUE THREAD

**Issue by GavinHuttley** [iqtree/piqtree#17]
as discussed earlier -- makes it easier to check they're being correctly input

**Comment by thomaskf** [comment]
DNA models:

JC, F81, K80, HKY, TN, TNe, K81, K81u, TPM2, TPM2u, TPM3, TPM3u, TIM, TIMe, TIM2, TIM2e, TIM3, TIM3e, TVM, TVMe, SYM, GTR

**Comment by thomaskf** [comment]
AA models:
Blosum62,cpREV,Dayhoff,DCMut,EAL,ELM,FLAVI,FLU,GTR20,HIVb,HIVw,JTT,JTTDCMut,LG,mtART,mtMAM,mtREV,mtZOA,mtMet,mtVer,mtInv,Poisson,PMB,Q.bird,Q.insect,Q.mammal,Q.pfam,Q.plant,Q.yeast,rtREV,VT,WAG
