### ISSUE TITLE
Leverage github actions to build a wheel for submission to pypi

### ISSUE THREAD

**Issue by khiron** [iqtree/piqtree#2]
We want to have the ability to rebuild the library for all 3 OSes such that we can publish to pypi as part of a release being triggered.

Gavin said that this should be possible to build a wheel as part of our CI so that it contains the linux/mac/windows specific libiqtree libraries in OS specific builds 

I'm not sure how to do this, and haven't had time to research that.

**Comment by rmcar17** [comment]
So far, I've set up a build GitHub action to generate x86_64 manylinux (only this I've verified) and musllinux wheels, as well as macos (x86_64 and arm64) wheels.

**Comment by rmcar17** [comment]
I've dropped support for musllinux (issues with cogent3 - numba dependency doesn't provide wheel) and arm linux (various issues - can't find eigen3 library on x86 and hanging on build step on ARM).

We do support manylinux2014_x86_64 (vast, vast majority of linux distributions), and both Intel and M1 macs. No support for windows (for now) as the libiqtree branch of IQTree does not support it yet.

**Comment by rmcar17** [comment]
Wheel submission to test pypi has been verified
