### ISSUE TITLE
Attach likelihood object to tree params when processing yaml

### ISSUE THREAD

**Issue by rmcar17** [iqtree/piqtree#27]
~The `_process_tree_yaml` function in `_iq_wrappers.py` is the place to do this!~

Now in `src/piqtree2/iqtree/_tree.py: _process_tree_yaml`

**Comment by rmcar17** [comment]
Base frequencies are now included in the yaml output (#40, #47)

**Comment by YapengLang** [comment]
I've modified the `_process_tree_yaml` function to attach the rate and motif parameters to the cogent3 tree object. 

These changes will now only apply to DNA models, excluding those in the Lie model list. I still need to explore those models' behaviour of the .yaml output further.

**Comment by YapengLang** [comment]
I will add tests for the branch length obtained from processing yaml.
