### ISSUE TITLE
Check the export of all 3 functions from all libraries in the stack

### ISSUE THREAD

**Issue by khiron** [iqtree/piqtree#4]
- [x] [ ] static library libiqtree.a exports all 3 functions
- [x] [ ] static library libiqtree.a doesn't require the other static libraries  (libkernelavx.a, libkernelfma.a, libkernelsse.a) 
- [x] [ ] we can make a C++ program that links libiqtree.a  and can call these functions (replicating Thomas's work)
- [x] [ ] the libiqtree_wrapper.so relocatable library exports all 3 functions
- [x] [ ] a python dummy project can call the libiqtree_wrapper.so and call one of those functions
- [x] [ ] we can call these functions in the pyiqtree library from a notebook

**Comment by rmcar17** [comment]
These goals have been achieved.
