### ISSUE TITLE
ENH: expose additional IQ-TREE functions

### ISSUE THREAD

**Issue by rmcar17** [iqtree/piqtree#41]
- [x] pairwise ml distances (.mldist file). Return in whatever in-memory data format is easiest - I'll need to convert this to a numpy array on my side of things anyway.
- [x] RapidNJ - (take in a vector of strings for taxa names, as well as pairwise distance matrix (vector of vector of doubles?)) return newick string
- [x] Model Finder - return model string for me to parse? what's easiest?

Anything else?

**Comment by thomaskf** [comment]
A function is added to also output the pairwise ml distance matrix when building a tree. Corresponding commit: https://github.com/iqtree/iqtree2/commit/f8935a695498c56f80aa5add4fec18659da8f831

**Comment by thomaskf** [comment]
ModelFinder function is now available for PiQTREE. 
Commit: https://github.com/iqtree/iqtree2/commit/80034a3cbc57a19fbd53b200b0e26e584c76f980

**Comment by thomaskf** [comment]
A function to build JC distance matrix is available.
Commit: https://github.com/iqtree/iqtree2/commit/ddb36faee8cf9012f4b8623ec4335ca4f81008b7

**Comment by thomaskf** [comment]
sorry, need to update the function (for the JC dist mat). Please don't use it yet.

**Comment by thomaskf** [comment]
The function to build the JC distance matrix is now available in C+++ side.
Commit: https://github.com/iqtree/iqtree2/commit/9dce368e9dd3a6a1e550f1d9cc479b1b0fed28ca

**Comment by thomaskf** [comment]
@rmcar17 @GavinHuttley, Could you clarify if we still need the function to report the ML distance matrix (i.e., the .mldist file) after the phylogenetic inference is completed? During the meeting, I understood that the first objective was changed to report the JC distance matrix directly from an alignment without inferring a tree. I’ve just done this.

**Comment by thomaskf** [comment]
The function to use Rapid-NJ to build a tree from a distance matrix is now available in C++ side.
The last commit: https://github.com/iqtree/iqtree2/commit/cf47d3617480fd5f466ec6ad7aee2c7a4b9aecd6

**Comment by thomaskf** [comment]
The declarations of these three functions:

```
// Perform phylogenetic analysis with ModelFinder
// on the input alignment (in string format)
// model_set -- a set of models to consider
// freq_set -- a set of frequency types
// rate_set -- a set of RHAS models
// rand_seed -- random seed, if 0, then will generate a new random seed
// output: modelfinder results in YAML format
string modelfinder(vector<string>& names, vector<string>& seqs, int rand_seed = 0,
                   string model_set = "", string freq_set = "", string rate_set = "");

// Build pairwise JC distance matrix
// output: a phylip-formated distance matrix (in string format)
string build_distmatrix(vector<string>& names, vector<string>& seqs);

// Using Rapid-NJ to build tree from a distance matrix
// input: a phylip-formated distance matrix (in string format)
// output: a newick tree (in string format)
string build_njtree(string dist_matrix);
```

**Comment by thomaskf** [comment]
If there is any bug, please kindly let me know. I have not tested the functions extensively. Many thanks @rmcar17 !

**Comment by rmcar17** [comment]
Thanks @thomaskf! I'll get to porting these over to the python side of things soon.

Re: mldist may as well keep as is for now

**Comment by GavinHuttley** [comment]
We don't need the ml , just the distance matrix

**Comment by GavinHuttley** [comment]
@GavinHuttley  move these into separate issues

**Comment by thomaskf** [comment]
@rmcar17 Updated declarations of the functions:

```
// Perform phylogenetic analysis with ModelFinder
// on the input alignment (in string format)
// model_set -- a set of models to consider
// freq_set -- a set of frequency types
// rate_set -- a set of RHAS models
// rand_seed -- random seed, if 0, then will generate a new random seed
// output: modelfinder results in YAML format
string modelfinder(vector<string>& names, vector<string>& seqs, int rand_seed = 0,
                   string model_set = "", string freq_set = "", string rate_set = "");

// Build pairwise JC distance matrix
// output: set of distances
// (n * i + j)-th element of the list represents the distance between i-th and j-th sequence,
// where n is the number of sequences
vector<double> build_distmatrix(vector<string>& names, vector<string>& seqs);

// Using Rapid-NJ to build tree from a distance matrix
// output: a newick tree (in string format)
string build_njtree(vector<string>& names, vector<double>& distances);
```

**Comment by rmcar17** [comment]
Awesome, thank you!
