### ISSUE TITLE
ENH: allow multithreading from IQ-TREE

### ISSUE THREAD

**Issue by rmcar17** [iqtree/piqtree#42]
The previous hurdle was that we couldn't use the openMP version of IQ-TREE because openMP did not respect the position independent code flag, meaning we couldn't use it as a dynamic library from Python. Requires investigation.

**Comment by aghozlane** [comment]
Dear authors of piqtree2,

Is there any progress to activate the multi-threading ? Current implementation is awesome, but I have too much data to use it.

Thanks !

**Comment by GavinHuttley** [comment]
Hi @aghozlane !
If you want to parallelise across multiple data sets, you can use cogent3 apps for that. We are working on docs to describe how to do this, but am happy to post content here if this would fit your needs.

**Comment by rmcar17** [comment]
For the multithreading from IQ-TREE use case, after being on the back-burner for some time (due to some linking issues) I've picked up development on this again (as of yesterday funnily enough). Currently, one major hurdle on linux has been resolved, have to do the same for macos. Don't have an ETA at this stage, but it is being worked on!

**Comment by aghozlane** [comment]
I would like to share with you some benchmark that we did. We start from a fasta with aligned sequence (one sequence per sample), we compute the genetic distance and we compute the tree. 
<img width="990" alt="image" src="https://github.com/user-attachments/assets/1d7ff2a5-0952-48e2-9856-509e1ec077d4">

Piqtree2 is the slowest approach for now. I don't think we did anything wrong, we followed the documentation. Any help to improve the computation speed would be awesome.

GTR, K80 and F81 are cogent3 basic workflow with different metrics

**Comment by rmcar17** [comment]
Thanks for benchmarking and sharing those figures! We are still relatively early days in this project's development (still pre a 1.0 release), but we are aiming to support multithreading from IQ-TREE's side in the near future. Hopefully should get a nice speedup once that's done!

**Comment by rmcar17** [comment]
Multithreading supported in the soon-to-be-release 0.4.0!
