### ISSUE TITLE
ENH: add Lie Markov models

### ISSUE THREAD

**Issue by rmcar17** [iqtree/piqtree#46]
@thomaskf if you could provide a list of the available Lie Markov models as well as their descriptions, then assign the issue to me and I'll add support for them as an enum.

Anything else we haven't included support for yet along those lines? Here was the previous issue #32

**Comment by thomaskf** [comment]
### Lie Markov models

| Model | Rev? | Freq | Note |
| -------- | ----------- | ----------- | ----------- |
|1.1 | Yes | 0 | equiv. to JC|
|2.2b | Yes | 0 | equiv. to K2P|
|3.3a | Yes | 0 | equiv. to K3P|
|3.3b | No | 0 | |
|3.3c | Yes | 0 | equiv. to TNe|
|3.4 | Yes | 1 | |
|4.4a | Yes | 3 | equiv. to F81|
|4.4b | Yes | 1 | |
|4.5a | No | 1 | |
|4.5b | No | 1 | |
|5.6a | No | 0 | |
|5.6b | No | 3 | |
|5.7a | No | 2 | |
|5.7b | No | 0 | |
|5.7c | No | 0 | |
|5.11a | No | 2 | |
|5.11b | No | 0 | |
|5.11c | No | 0 | |
|5.16 | No | 1 | |
|6.6 | No | 1 | equiv. to STRSYM for strand-symmetric model (Bielawski and Gold, 2002)|
|6.7a | No | 3 | F81+K3P|
|6.7b | No | 3 | |
|6.8a | No | 3 | |
|6.8b | No | 1 | |
|6.17a | No | 1 | |
|6.17b | No | 1 | |
|8.8 | No | 3 | |
|8.10a | No | 3 | |
|8.10b | No | 1 | |
|8.16 | No | 3 | |
|8.17 | No | 3 | |
|8.18 | No | 3 | |
|9.20a | No | 2 | |
|9.20b | No | 0 | Doubly stochastic|
|10.12 | No | 3 | |
|10.34 | No | 3 | |
|12.12 | No | 3 | equiv. to UNREST (unrestricted model)|

Column `Rev?` shows whether the model is reversible or not. Column `Freq` shows the number of free base frequencies. 0 means equal base frequency; 1 means f(A)=f(G) and f(C)=f(T); 2 means f(A)+f(G)=0.5=f(C)+f(T); 3 means unconstrained frequencies.

These models include the frequency specification, so the frequency parameters do not need to be added.

For example: 8.8+G , but not 8.8+F+G
