### ISSUE TITLE
BUG: can't pickle the app

### ISSUE THREAD

**Issue by GavinHuttley** [iqtree/piqtree#53]
This is needed in order to run parallel analyses at the python level

```python
import pickle
from cogent3 import get_app

app = get_app("piqtree_phylo", model="GTR")
z = pickle.dumps(app)
```
Gives the error `_pickle.PicklingError: Can't pickle <class 'piqtree2.iqtree._tree.build_tree'>: it's not the same object as piqtree2.iqtree._tree.build_tree`

**Comment by rmcar17** [comment]
Tricky... I can easily see how to make classes pickleable but nothing immediately obvious for functions... I'll take a look

**Comment by rmcar17** [comment]
Turned out to be an issue with declaring an app of a different name to the original function
