### ISSUE TITLE
pre-alpha release feature target

### ISSUE THREAD

**Issue by GavinHuttley** [iqtree/piqtree#6]
- [x]  `piqtree2.robinson_foulds(*trees: cogent3.PhyloNode) -> tuple[int,...]`
- [x] `piqtree2.random_tree(num_taxa: int, tree_mode: enum, num_trees: int, rand_seed: typing.Optional[int]=None) -> tuple[cogent3.PhyloNode]` (seed should go into result trees `.params["rand_seed"])
- [x] `piqtree2.build_tree(aln: cogent3.Alignment, rand_seed:..., <params to control execution>) -> cogent3.PhyloNode`
- [x] `piqtree2.fit_tree(aln: cogent3.Alignment, tree: cogent3.PhyloNode, <params to control execution>) -> cogent3.PhyloNode`

**Comment by GavinHuttley** [comment]
example for `piqtree2.build_tree()`
```python
aln  = ...
tree = piqtree2.build_tree(aln, model_name="GTR", rate_het="G", freq_code: enum="F", )
# F is from alignment, FO is optimised, FQ=all states equally frequent"
# default for rate_het is None
tree.get_figure()
```

**Comment by rmcar17** [comment]
We now support rate_type and freq_type!
