### ISSUE TITLE
ultrafast bootstrap support

### ISSUE THREAD

**Issue by GavinHuttley** [iqtree/piqtree#75]
needs exposed API on libqitree side, @thomaskf suggested an integer argument with minimum value of 1000. On the python side, I suggest an argument `boostrap: int | None`.

**Comment by thomaskf** [comment]
Done. The updated definition of the function build_tree():

```
string build_tree(vector<string>& names, vector<string>& seqs, string model, int rand_seed = 0, int bootstrap_rep = 0);
```

if `bootstrap_rep` >= 1000, then bootstrapping is performed.

**Note on the output**

When bootstrapping option is used, both the optimal tree and the consensus tree with bootstrap values will be reported. 

For example:

```
PhyloTree:
 newick: (0:0.1217553654,(1:0.1243297034,2:0.1248580719)100:0.07164107134,(3:0.1583652739,((4:0.1443353348,((5:0.1905063055,6:0.2124297088)46:0.02512041996,(7:0.1785286386,8:0.1512279839)100:0.06175781451)46:0.03404655353)98:0.05028282564,(((9:0.1355947955,(10:0.0761888798,(11:0.0689011000,12:0.0815710002)99:0.03154162773)69:0.02352451041)89:0.02892423234,(13:0.0540524626,14:0.0711660824)100:0.08109891438)98:0.04038956276,(15:0.1321233784,16:0.1117587477)100:0.03868965858)100:0.08513057544)100:0.08177794256)100:0.06139226242);
```
```
contree: (0:0.1217562708,(1:0.1243286846,2:0.1248585005)100:0.07164069618,(3:0.1583655676,((4:0.1443332280,((5:0.1905065532,6:0.2124309149)46:0.02511623366,(7:0.1785276646,8:0.1512288609)100:0.06175630077)46:0.03404531447)98:0.05028213865,(((9:0.1355861521,(10:0.0761751986,(11:0.0688933874,12:0.0815584597)99:0.03152775838)69:0.02350966413)89:0.028914132,(13:0.0540510001,14:0.0711655751)100:0.08109692108)98:0.04038505699,(15:0.1321231192,16:0.1117598400)100:0.03868906502)100:0.08513493946)100:0.08177687535)100:0.06139173791);
```

**Comment by GavinHuttley** [comment]
add to the python docstring this is the ultrafast (not conventional) bootstrap

**Comment by thomaskf** [comment]
An example of the output tree with internal node name and bootstrap value:

(LngfishAu:0.1217528847,(LngfishSA:0.1243392755,LngfishAf:0.1248537935)a/100:0.0716474117,(Frog:0.1583752300,((Turtle:0.1443378788,((Sphenodon:0.1905253603,Lizard:0.2124284778)47:0.0251045589,(Crocodile:0.1785210461,Bird:0.1512283652)b/100:0.0617524344)c/52:0.0340400728)98:0.0502915801,(((Human:0.1355910728,(Seal:0.0761881284,(Cow:0.0688996656,Whale:0.0815730950)98:0.0315442025)68:0.0235264023)90:0.0289264381,(Mouse:0.0540505484,Rat:0.0711670714)100:0.0811033740)98:0.0403864985,(Platypus:0.1321376216,Opossum:0.1117587547)99:0.0386906708)100:0.0851266331)100:0.0817785451)100:0.0613932200);
