### ISSUE TITLE
ENH: making the user experience simpler

### ISSUE THREAD

**Issue by GavinHuttley** [iqtree/piqtree#84]
.Users should not have to do imports from `piqtree2` in order to use the apps. This means we need to make it easy for them to specify what the models are, for instance, that they want to use. The attached patch addresses this.

# specify a substitution model with a string

I added a new function, get_model, to the _substitution_model module. I modified the _model.Model class to call this on creation, I'm changing the type hint for this class from the enum to a string.

I modified the app `piqtree2._app.piqtree_phylo` so that it is now a class. The reason for this is that at least the user gets useful help when they use `app_help()` in the sense that the signature is now meaningful.

It also means that if the user inputs an incorrect value, the exception happens at the line where the app is created and not on execution with some data.

[usability.patch](https://github.com/user-attachments/files/17405000/usability.patch)

**Comment by rmcar17** [comment]
Agree with the idea, but the reality of the implementation is a bit more complicated. The full model string definition is available [here](http://www.iqtree.org/doc/Substitution-Models) - this approach would ignore base frequencies, rate heterogeneity, and things we haven't implemented yet like model parameterisation (i.e. fixing some substitution rates). It may be a better idea to forego the model enums etc. and just rely on the strings.
